services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin  # Set your MinIO root user
      - MINIO_ROOT_PASSWORD=minioadmin123  # Set your MinIO root password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio_data:/data  # Data storage volume
    restart: unless-stopped

  minio-console:
    image: minio/mc:latest
    container_name: minio_console
    depends_on:
      - minio
    # entrypoint: /bin/sh -c 'while ! mc alias set myminio http://minio:9000 minioadmin minioadmin123; do sleep 3; done; mc admin info myminio'
    entrypoint: /bin/bash -c "
      sleep 10;
      /usr/bin/mc config --quiet host add alchemyminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb --quiet alchemyminio/bronze;
      /usr/bin/mc mb --quiet alchemyminio/silver;
      /usr/bin/mc mb --quiet alchemyminio/gold;"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:
